- name: AE PC member of NDSS 2025
- name: Reviewer of IEEE Security & Privacy 2024, PPAI 2024
- name: PC member of ACM FAccT Conference 2023, 2022
- name: PC member of PAIR2Struct workshop in ICLR 2022
- name: Sub-reviewer for IEEE S&P, ACM CCS